name: "Validate pull request"
on: pull_request
jobs:
  prettier-validation:
    runs-on: ubuntu-latest
    name: Prettier validation
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
      - name: instal dependencies
        run: npm i
      - name: Run prettier
        run: npx prettier --list-different .
  typescript-validation:
    runs-on: ubuntu-latest
    name: Try to compile ts
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
      - name: instal dependencies
        run: npm i
      - name: Run typescirpt compilation
        run: tsc -p .
  run-tests-on-linux:
    runs-on: ubuntu-latest
    name: Run tests on linux
    needs:
      - typescript-validation
      - prettier-validation
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
      - name: instal dependencies
        run: npm i
      - name: Run tests
        run: npm test
  run-tests-on-mac:
    runs-on: macos-latest
    name: Run tests on macos
    needs:
      - typescript-validation
      - prettier-validation
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
      - name: instal dependencies
        run: npm i
      - name: Run tests
        run: npm test
  run-tests-on-windows:
    runs-on: windows-latest
    name: Run tests on windows
    needs:
      - typescript-validation
      - prettier-validation
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
      - name: instal dependencies
        run: npm i
      - name: Run tests
        run: npm test
